apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: myapp
spec:
  selector:
    app: deployment  # Ensure this matches the label in your mongo deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
