apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: myapp
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /tmp/mongo-storage    # This is the path on your local machine
    type: DirectoryOrCreate
